#!/usr/bin/env bash
###############################################################################
# A simple initrd extractor...
# Garry Iglesias 2013-2016
###############################################################################
set -Cue
###############################################################################
readonly LAUNCH_DIR="$(pwd)"
#######################################
nsk-error () { echo "Error:" "$@" >&2 ; exit 1 ; }
###############################################################################
(( !EUID )) || nsk-error "You must have root privilege to run this script."
###############################################################################
# Parameters:
XINITRD_SOURCE_IMAGE="${1:-}"
XINITRD_TARGET_ROOT="${2:-}"
[[ -n "$XINITRD_SOURCE_IMAGE" ]] \
    || nsk-error "No Source image specified !"
[[ -n "$XINITRD_TARGET_ROOT" ]] \
    || XINITRD_TARGET_ROOT="$LAUNCH_DIR"
###############################################################################
[[ "$XINITRD_SOURCE_IMAGE" == /* ]] \
    || XINITRD_SOURCE_IMAGE="$LAUNCH_DIR/$XINITRD_SOURCE_IMAGE"
[[ -f "$XINITRD_SOURCE_IMAGE" ]] \
    || nsk-error "Source image not found: '$XINITRD_SOURCE_IMAGE'"
[[ -d "$XINITRD_TARGET_ROOT" ]] \
    || mkdir -p "$XINITRD_TARGET_ROOT" \
    || nsk-error "Cannot create target directory: '$XINITRD_TARGET_ROOT'"
###############################################################################
# Extract:
cd "$XINITRD_TARGET_ROOT" \
    && gzip -dc "$XINITRD_SOURCE_IMAGE" \
        | cpio -i -d -H newc --no-absolute-filenames \
	|| nsk-error "Failed unpacking source initrd image!"
